## 大域脱出

## 問題
- 基本問題11

### 大域脱出
- breakではできない、２重ループから一気に抜ける方法。  
- どんなに深くても「throw ラベル名」でcatch内から一気に脱出できる。  
```
catch :label do
  0.upto(3) do |x|
    0.upto(3) do |y|
      puts "x=#{x}, y=#{y}"
      throw :label if y == 1
    end
  end
end

x=0, y=0
x=0, y=1
```

```
def foo
  throw :exit
end

catch(:exit) {
  foo
  p 1 #これは実行されない
}
p 2 #=> 2
```
